### PR TITLE
Remove the binary netCDF files from the repo.

### PR DESCRIPTION
**Pull request by timspainNERSC**
# Remove the binary netCDF files from the repo.
## Partially fixes \#379

---

# Change Description

Removes the binary netCDF files from the repository.

The files
```
init_rect20x30.nc
init_rect30x30.nc
```
can be recreated using their respective scripts
```
make_init_rect20x30.py
make_init.py
```

These and all netCDF files that depend on the ERA5 and TOPAZ4 reanalyses can be found at [ftp://ftp.nersc.no/nextsim/netCDF](ftp://ftp.nersc.no/nextsim/netCDF). These include the atmosphere and ocean boundary files used in the year-long reference run described by `config_june23.cfg`.
```
init_25km_NH.nc
init_rect20x30.nc
init_rect30x30.nc
init_topaz128x128.nc
25km_NH.ERA5_2010-01-01_2011-01-01.nc
25km_NH.TOPAZ4_2010-01-01_2011-01-01.nc
ERA5_2010-01-01_2011-01-01.nc
TOPAZ4_2010-01-01_2011-01-01.nc
```

### CODE REVIEW

**Review by MarionBWeinzierl — APPROVED** [review]
It makes sense to remove these, as long as we have the info in the docs/readme how to create them.

**Comment by timspainNERSC** [comment]
> It makes sense to remove these, as long as we have the info in the docs/readme how to create them.

See issue #379 and branch `issue379_ncgenerator`.

**Comment by TomMelt** [comment]
Perfect. Thanks Tim :tada:

What do we mean by partially fixes #379 ? this looks like a complete fix to me or am I missing something.

**Comment by timspainNERSC** [comment]
> What do we mean by partially fixes #379 ? this looks like a complete fix to me or am I missing something.

I want to add scripting to the CMakeLists to regenerate the netCDF files that don't depend on external data.

Also, I rather thought that one of the tests depended on one of the deleted files. Apparently not.

**Pull request merged**
