### PR TITLE
Stress advection

### PR DESCRIPTION
**Pull request by einola**
# Stress advection code for tensor components only
### Task List
- [ ] Defined the tests that specify a complete and functioning change (*It may help to create a [design specification & test specification](../../../wiki/Specification-Template)*)
- [ ] Implemented the source code change that satisfies the tests
- [ ] Documented the feature by providing worked example
- [ ] Updated the README or other documentation
- [ ] Completed the pre-Request checklist below

---
# Change Description

This PR adds support for the transport of stresses. We have tested this in the old development setups Thomas and Piotr used, but not in the full model. Such tests can only be done after #378 is addressed, but this code is crucial for addressing that issue, so we need to merge it now. We could consider merging this into a separate branch, which addresses #378.

## Added missing functions for DGTransport<8>:

mostly just adding the explicit template definitions, such as
  ``template class DGTransport<8>;``

the only part where new code was required in DGTransport.cpp
  ``leftedgeofcell``, ``rightedgeofcell``, ``topedgeofcell``, ``bottomedgeofcell``

these functions restrict an element-DG function to the edge-DG functions by translating the basis functions 1,(x-1/2),(y-1/2),(x-1/2)(y-1/2), ... to the corresponding functions on the edges, 1,(t-1/2),(t-1/2)^2-1/12. Therefore, the cell-edge functions are evaluated for x=0 (left), x=1 (right), y=0 (bottom), and y=1 (top) and the corresponding edge basis functions are collected.

## Added a new DGTransport-Class to DynamicsKernel

``Nextsim::DGTransport<CG2DGSTRESS(CGdegree)>* stresstransport;``

``CG2DGSTRESS`` computes the number of DG-stress unknowns per element depending on the CG discretization of the velocity.

This stresstransport is initialized along with dgtransport (used for the advection)

## Added first version of stress transport to DynamicsKernel::update

Currently commented out.

---
# Test Description

We still need to implement propper testing of this code. "Casual testing", using the old development setup shows that it should work.

---

# Documentation Impact

No documentation impact.

---
# Other Details

None

---
### Pre-Request Checklist

- [ ] The requirements of this pull request are fully captured in an issue or design specification and are linked and summarised in the description of this PR
- [ ] No new warnings are generated
- [ ] The documentation has been updated (or an issue has been created to track the corresponding change)
- [ ] Methods and Tests are commented such that they can be understood without having to obtain additional context
- [ ] This PR/Issue is labelled as a bug/feature/enhancement/breaking change
- [ ] File dates have been updated to reflect modification date
- [ ] This change conforms to the conventions described in the README

### CODE REVIEW

**Comment by einola** [comment]
This is the stress advection code Thomas developed, and I've merged it into the new structure. It doesn't do anything yet but is needed for issue #378. We need to decide if we should merge this into develop or into the issue branch for issue #378 (which still doesn't exist).

**Comment by timspainNERSC** [comment]
I think this should be merged into the branch for issue #378 (coming soon!)

**Comment by timspainNERSC** [comment]
> I think this should be merged into the branch for issue #378 (coming soon!)

The branch for solving issue #378 is `issue378_dynamicsswitcher2` which is referenced in PR #477.

**Comment by timspainNERSC** [comment]
The main commit 7058b88 was cherry picked (and deconflicted) on to the `issue378_dynamicsswitcher2` branch.

**Comment by timspainNERSC** [comment]
The current state of `issue378_dynamicsswitcher2` builds. Are any of the other commits on this branch critical and need to be ported over?

(There are too many conflicts to merge or rebase the branches.)

**Comment by einola** [comment]
`issue378_dynamicsswitcher2` looks fine after the cherry picking. It was only 7058b8842c251020e89325d4f5ba68487b24079a that was needed in the end.

Closing this PR as a result.

**Pull request closed without merging**
