### PR TITLE
Set up periodic Docker build

### LINKED ISSUE #618: Set up periodic workflow for Docker build
We should set up a GitHub Actions workflow that periodically (e.g., once per month) builds the Docker image used by nextSIM-DG for testing. This will enable us to track updates to XIOS (for example).

Possibly useful:
* https://docs.github.com/en/packages/quickstart
* https://stackoverflow.com/questions/75926611/github-workflow-to-push-docker-image-to-ghcr-io

### PR DESCRIPTION
**Pull request by jwallwork23**
# Set up periodic Docker build
## Fixes #618

# Change Description

Closes #618.
Partially addresses #541.

The Docker image will be rebuilt:
* Every 3 months at 00:00 on the first day of the month.
* When a commit is pushed to an open PR that changes `.github/workflows/docker.yml`.

The PR also adds a YAML file for the Spack build, some minor Dockerfile optimisations, comments, and formatting changes.

I also renamed the test suite YAML file to `test_suite.yml`.

### CODE REVIEW

**Comment by jwallwork23** [comment]
Note that I had to give the CI of this repo push permissions in https://github.com/orgs/nextsimhub/packages/container/nextsimdg-dev-env/settings.

**Comment by jwallwork23** [comment]
I also added catch2, trilinos and zoltan to the Spack config to support https://github.com/nextsimhub/domain_decomp/issues/30.

**Comment by jwallwork23** [comment]
There's now potential duplicity between `spack.yaml` and `Dockerfiles/spack*.yaml`. Any thoughts on whether we should remove or merge some of them?

**Comment by jwallwork23** [comment]
Apologies for adding you as reviewer before this was ready @TomMelt. It's now ready for review!

**Comment by jwallwork23** [comment]
Closes #541, as discussed on that issue.

**Review by TomMelt — APPROVED** [review]
thanks @jwallwork23

**Pull request merged**
