### PR TITLE
Add MPI to Parametric Grid Implementation

### LINKED ISSUE #448: Move MPI Parallelisation to ParGrid and remove RectGrid
Following the discussion in #442 , we need to move the MPI parallelisation done in #331 over to the parametric grid, and then remove the rectangular grid.

This should be done after #331 and #432 were merged into `develop`.

### PR DESCRIPTION
**Pull request by MarionBWeinzierl**
This PR closes #448.

After #331 added MPI parallelisation for thermodynamics on the RectGrid, this PR does the same for the Parametric grid. This should then check off the second task in #120 (_"MPI parallelization of thermodynamics where all operations, except for I/O, are local to an MPI rank"_)

That includes:
- [x] Check which parts of #331 can be transferred to the Parametric grid and transfer them
- [x] #513 
- [x] #515 
- [ ] Implement/fix parallel IO for the NetCDF files (`ParaGridIO`)
- [ ] Implement boundary conditions (communication using ghost layers/halos)
- [ ] Implement sending values in batches
- [ ] Extend tests 
- [ ] Further TODOs 
- [ ] Potentially remove the RectGrid

### CODE REVIEW

**Comment by MarionBWeinzierl** [comment]
We discussed what test cases best to use (see also #505) , and that it would be good to have a simple test case which does not include all the corner cases which the realistic example runs have. @timspainNERSC provided a restart file for a simple example in #506 .

**Comment by TomMelt** [comment]
When this PR is merged it should also fix #534

**Comment by MarionBWeinzierl** [comment]
@TomMelt , do you want to work from this PR or shall we close it?

**Comment by TomMelt** [comment]
> @TomMelt , do you want to work from this PR or shall we close it?

we can close it :) I have started a new PR #560

**Pull request closed without merging**
