### PR TITLE
Simple 2D ParametricGrid restart file

### PR DESCRIPTION
**Pull request by timspainNERSC**
# Simple 2D ParametricGrid restart file
## Fixes \#505

Adds a script to generate a simple, two dimensional restart file with the ParametricGrid structure. Also adds the config time hook to generate the file.

### CODE REVIEW

**Comment by MarionBWeinzierl** [comment]
Thanks for adding the corrected config file, @timspainNERSC . Could you please clarify: Do I see it correctly that #511 has to be merged first for this to work? Currently, I am getting `terminate called after throwing an instance of 'std::out_of_range'` when trying to run this example.

**Comment by timspainNERSC** [comment]
> Thanks for adding the corrected config file, @timspainNERSC . Could you please clarify: Do I see it correctly that #511 has to be merged first for this to work? Currently, I am getting `terminate called after throwing an instance of 'std::out_of_range'` when trying to run this example.

That should have been fixed by commit `ae148e9` in this branch. It was for me, at least.

There shouldn't be any problem using the config file you posted on Slack, as long as you change the value of `IceThermodynamicsModule` to `Nextsim::ThermoIce0`.

**Comment by MarionBWeinzierl** [comment]
Ah, I got it to run now, error on my side.

**Review by MarionBWeinzierl — APPROVED** [review]
Works and looks good for me, useful test case for parametric grid.

**Pull request merged**
