### PR TITLE
Updating docs branch from develop

### PR DESCRIPTION
**Pull request by auraoupa**
# Update docs branch

First step before answering \#436

### CODE REVIEW

**Comment by MarionBWeinzierl** [comment]
Could you please briefly describe what this PR does? Thank you!

**Comment by auraoupa** [comment]
I am rebasing the docs branch that is very outdated so that I can modify the README and merge it back to the develop branch in a second time

**Review by MarionBWeinzierl — APPROVED** [review]
I am not able to go through all 263 files, but as the tests run through I am reasonably confident that this should be ok....

**Comment by auraoupa** [comment]
That shows how outdated the docs branch was ! They all must have been validated at some point when they were introduced to the develop branch

**Review by stephanieleroux — APPROVED** [review]

**Pull request merged**
