### PR TITLE
Use `size_t` for sizes in XIOS interface

### LINKED ISSUE #562: XIOS error handling
just a thought, not necessarily for this PR. Would it be sensible to throw an exception if any of the getter objects are still `NULL`? Ill be honest... I didn't really check what happens if `xios` getters fail. If `xios` throws the error anyway then it may not be necessary.

_Originally posted by @TomMelt in https://github.com/nextsimhub/nextsimdg/pull/555#discussion_r1607849575_

### LINKED ISSUE #572: Use `size_t` for sizes in XIOS API rather than `int`
The `Xios` class uses `int` for sizes, where it would be preferable to use `size_t`.

### PR DESCRIPTION
**Pull request by jwallwork23**
# Use `size_t` for sizes in XIOS interface
### Task List
- [x] Defined the tests that specify a complete and functioning change (*It may help to create a [design specification & test specification](../../../wiki/Specification-Template)*)
- [x] Implemented the source code change that satisfies the tests
- [x] Documented the feature by providing worked example
- [x] Updated the README or other documentation
- [x] Completed the pre-Request checklist below

---
# Change Description

Use `size_t` for sizes in the XIOS interface, rather than `int`, for consistency with the rest of the code base. Also, throw exceptions if the getter methods return null pointers.

NOTE: #559 and #574 will need to be merged first.

---
# Test Description

Updated the tests accordingly.

---
### Pre-Request Checklist

- [x] The requirements of this pull request are fully captured in an issue or design specification and are linked and summarised in the description of this PR
- [x] No new warnings are generated
- [x] The documentation has been updated (or an issue has been created to track the corresponding change)
- [x] Methods and Tests are commented such that they can be understood without having to obtain additional context
- [x] This PR/Issue is labelled as a bug/feature/enhancement/breaking change
- [x] File dates have been updated to reflect modification date
- [x] This change conforms to the conventions described in the README

### CODE REVIEW

**Comment by jwallwork23** [comment]
Ready for review, but #559 and #574 will need to be merged first so not assigning a reviewer yet.

**Review by timspainNERSC — CHANGES_REQUESTED** [review]
Could you add some sort of prefix to the exception messages so that the user knows they came from within XIOS/Xios.cpp? (Assuming this isn't prepended by a higher level try/catch).

**Comment by timspainNERSC** [comment]
Perfect!

**Review by timspainNERSC — APPROVED** [review]

**Comment by jwallwork23** [comment]
Thanks! Will update file dates and then merge.

**Pull request merged**
